### ISSUE TITLE
FastText model broken link

### ISSUE THREAD

**Issue by ilivans** [deepmipt/intent_classifier#2]
The provided URL of pretrained FastText embeddings (http://lnsigo.mipt.ru/export/intent/reddit_fasttext_model.tar.gz) is either broken or available only on your local net.

This is what `reddit_fasttext_model.tar.gz` looks like for me
```
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.12.2</center>
</body>
</html>
```

And the training script raises an error:
> RuntimeError: ('Looks like the `EMBEDDINGS_URL` variable is set incorrectly', ReadError('file could not be opened successfully',))

**Comment by dilyararimovna** [comment]
Yes, it seems that this pre-trained model was deleted from the storage.
You can either train and provide your own fasttext model or you can use pre-trained model from `https://github.com/facebookresearch/fastText/blob/master/pretrained-vectors.md`

Please, be attentive with fasttext versions.
Also you can try to use intent classification model (the same) from pre-alfa release of the DeepPavlov
`https://github.com/deepmipt/DeepPavlov`
