### ISSUE TITLE
RuntimeError: No pretrained fasttext intent_model provided

### ISSUE THREAD

**Issue by ilivans** [deepmipt/intent_classifier#3]
`train.py` script with default configuration file `config.json` raises the next error:

```
Traceback (most recent call last):
  File "train.py", line 49, in <module>
    model = KerasMulticlassModel(opt)
  File "/home/ilivans/projects/intent_classifier/intent_model/multiclass.py", line 73, in __init__
    embedding_url='http://lnsigo.mipt.ru/export/intent/reddit_fasttext_model.tar.gz')
  File "/home/ilivans/projects/intent_classifier/intent_model/embedding_inferable.py", line 38, in __init__
    self.load(embedding_fname, embedding_url)
  File "/home/ilivans/projects/intent_classifier/intent_model/embedding_inferable.py", line 83, in load
    raise RuntimeError('No pretrained fasttext intent_model provided')
RuntimeError: No pretrained fasttext intent_model provided
```

I thought it should download the fasttext model and it actually goes through [this line](https://github.com/deepmipt/intent_classifier/blob/511277fe60fe2f71f8fc0afc989bbef01e9ce81d/intent_model/multiclass.py#L72) but fails [here](https://github.com/deepmipt/intent_classifier/blob/511277fe60fe2f71f8fc0afc989bbef01e9ce81d/intent_model/embedding_inferable.py#L83) requiring embedding file name. It looks like the problem can be solved just by passing `embedding_fname` argument to the `EmbeddingInferableModel` constructor.

**Comment by dilyararimovna** [comment]
Thank you!
This is already fixed. 
I also provided embedding file for pre-trained model on SNIPS dataset.
